### ISSUE TITLE
POK-16- 🧹 Chore -  chore: Add CSS Reset

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/vanilla-pokedex#16]
# Add `CSS Reset` 

Each browser has its own definition for each of the core HTML elements. So when we create a `<div>` and render it in Chrome it might not necessarily render the same way in Safari. That's where CSS resets come in. These are special styles designed to normalize the styling of core HTML elements across browsers. And luckily adding them is just a matter of copy and paste. 

There are many CSS resets, but I prefer the OG [Reset CSS](https://meyerweb.com/eric/tools/css/reset/). 

## Add reset styles to `styles.css`
In our top-level CSS file add the following:

```css
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
        box-sizing: border-box;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

I've also added `box-sizing: border-box` to the styling. You should google this and understand why its important.
